name = "mbti-test"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# 环境变量在 Cloudflare Dashboard 中设置
# ZY_PID, ZY_PRIVATE_KEY, ZY_PUBLIC_KEY, ZY_PRICE

# KV 存储用户数据
[[kv_namespaces]]
binding = "MBTI_USERS"
id = "0272b12877264d808bec5fbee5f4db93"

[[d1_databases]]
binding = "MBTI_DB"
database_name = "mbti"
database_id = "1ab7b8ed-ca7e-4efc-ba94-7d73e0e5886d"
